/**
 * Meetings capability (ADR-018) — shared types.
 *
 * A "meeting" is memory-native (D1): a `session_key` + a transcript ingested as a
 * `SourceDocument(kind:"transcript")` + summary `CognitiveRecord`s. This module is
 * account-gated (D7) and models the full four-level sharing ladder (D8).
 *
 * The service depends on an injected {@link MeetingsMemoryPort} + {@link MeetingSummarizer}
 * so M0 is unit-testable in isolation and the real-engine adapter + the server-managed
 * summarizer can be finalized after Codex's provider work lands (see ADR §"LLMRunner adjustment").
 */

/** D8 sharing ladder. Extends the current `"private" | "org"` `MemoryVisibility`. */
export type MeetingVisibility = "private" | "team" | "org" | "public";

export interface MeetingAttendee {
  /** A BrainRouter handle / email string (Track uses bare handle strings today). */
  handle: string;
  displayName?: string;
}

export interface MeetingActionItem {
  title: string;
  assignee?: string;
  due?: string;
}

/** A section-based summary template (ported design from Meetily's JSON templates). */
export interface MeetingSummaryTemplate {
  name: string;
  sections: Array<{
    title: string;
    instruction: string;
    format: "paragraph" | "list" | "table";
  }>;
}

export interface MeetingSummaryResult {
  markdown: string;
  actionItems: MeetingActionItem[];
  /** BCP-47 language the summary was produced in. */
  language?: string;
}

/** Injected summarizer — a per-org routed call today; the server-managed provider after Codex. */
export interface MeetingSummarizer {
  summarize(input: {
    transcript: string;
    template?: MeetingSummaryTemplate;
    language?: string;
    orgId: string;
  }): Promise<MeetingSummaryResult>;
}

/**
 * The minimal memory surface the service needs. Backed in production by the memory
 * engine (`ingestSource`, `upsertEngineeringMemory`, `store.linkRecordSources`,
 * `sharing.setMemoryVisibility`) + the new `meeting_shares` token store. Kept as a
 * narrow port so M0 is testable and the engine adapter is a thin, swappable layer.
 */
export interface MeetingsMemoryPort {
  /** Ingest the raw transcript as a chunked, citable `SourceDocument(kind:"transcript")`. */
  ingestTranscript(input: {
    userId: string;
    orgId: string;
    meetingId: string;
    sessionKey: string;
    text: string;
  }): Promise<{ sourceId: string; chunkIds: string[] }>;

  /** Write a summary `CognitiveRecord` through the redaction + length chokepoint. */
  upsertSummaryRecord(input: {
    userId: string;
    orgId: string;
    sessionKey: string;
    content: string;
    metadata: Record<string, unknown>;
  }): Promise<{ recordId: string }>;

  /** Link the summary record to the transcript's source chunks (graph provenance). */
  linkRecordSources(userId: string, recordId: string, chunkIds: string[]): Promise<void>;

  /** Set the backend visibility scope (private/team/org). `teamId` required for team. */
  setVisibility(input: {
    recordId: string;
    userId: string;
    orgId: string;
    teamId?: string;
    visibility: Exclude<MeetingVisibility, "public">;
  }): Promise<boolean>;

  /** Mint a revocable public share token for the summary (public scope only). */
  createShareToken(input: {
    recordId: string;
    orgId: string;
    createdBy: string;
    expiresAt?: string;
  }): Promise<{ token: string }>;

  /** Revoke every active public share token for a record. Returns count revoked. */
  revokeShareTokens(recordId: string): Promise<number>;
}

export interface RecordMeetingInput {
  /** Account-gated (D7): both required — a meeting cannot be stored signed-out. */
  userId: string;
  orgId: string;
  /** Stable meeting id (`meeting-<uuid>`); generated by the caller if omitted-safe. */
  meetingId: string;
  sessionKey: string;
  title: string;
  transcript: string;
  attendees?: MeetingAttendee[];
  /** ISO calendar date of the meeting. */
  date?: string;
  template?: MeetingSummaryTemplate;
  language?: string;
  /** Initial sharing scope; defaults to `"private"`. */
  scope?: MeetingVisibility;
  /** Required when `scope === "team"`. */
  teamId?: string;
  /** Optional expiry for a `"public"` share. */
  shareExpiresAt?: string;
}

export interface MeetingShareState {
  scope: MeetingVisibility;
  teamId?: string;
  /** Present only when scope is `"public"`. */
  publicToken?: string;
}

export interface MeetingRecordResult {
  meetingId: string;
  recordId: string;
  sourceId: string;
  chunkIds: string[];
  actionItems: MeetingActionItem[];
  share: MeetingShareState;
}
